### ISSUE TITLE
Add version to install banner and JavaScript files

### ISSUE THREAD

**Issue by StephenCWills** [GridProtectionAlliance/SystemCenter#10]
This should just require calling a couple PowerShell scripts from the csproj file.

@clackner-gpa You mentioned versioning the JavaScript files as well. Can you provide some details?

**Comment by StephenCWills** [comment]
Version numbers added to the installer with 33b5933.

I don't know anything about versioning for JavaScript files. Is this about how the browser caches the scripts?

**Comment by clackner-gpa** [comment]
@StephenCWills This has been addressed. The issue was the version number in the webUI used to be a static string. We changed the Layout to use the version of `SystemCenter.exe` instead. (latest change that added Minor version number was 33b5933 )

**Comment by StephenCWills** [comment]
> @StephenCWills This has been addressed. The issue was the version number in the webUI used to be a static string. We changed the Layout to use the version of `SystemCenter.exe` instead. (latest change that added Minor version number was [33b5933](https://github.com/GridProtectionAlliance/SystemCenter/commit/33b59334e26e44dc16baa21a72a19013fb8a1751) )

Gotcha, thanks.
