### ISSUE TITLE
Installer allows multiple instances to be installed simultaneously

### ISSUE THREAD

**Issue by StephenCWills** [GridProtectionAlliance/SystemCenter#11]
This helps to explain why oftentimes our latest updates do not get applied when we install the latest version for testing. The installer should either uninstall the previous version or display an error message asking the user to uninstall the previous version. This likely has something to do with the `UpgradeCode` in the WiX installer build script.

**Comment by clackner-gpa** [comment]
This Issue required a change in the versioning logic. It has been fixed in SystemCenter (`02ce8a5`)
Nightly Builds will now increment the `buildnumber`. We possibly have to sync versions across PQ products at some point.
