### ISSUE TITLE
Tabs are hidden if they cannot fit on page

### ISSUE THREAD

**Issue by StephenCWills** [GridProtectionAlliance/SystemCenter#13]
If the browser window is too small to display all tabs, the tabs will simply be clipped, and there is no way to open them without resizing the browser or changing the zoom level.

Here is a page with hidden tabs.
![image](https://user-images.githubusercontent.com/9203145/118851278-98ee5880-b89f-11eb-9c3c-66c160acebd4.png)

Here is the same page, but zoomed out so the tabs are visible.
![image](https://user-images.githubusercontent.com/9203145/118851476-ccc97e00-b89f-11eb-8e3f-1b7fab6bea4d.png)

**Comment by clackner-gpa** [comment]
See #14

**Comment by StephenCWills** [comment]
I'm not sure why this was closed, unless you think that fixing #14 will simultaneously resolve this issue as well. It's fine if you can fix them at the same time, but I still see them as separate issues.

**Comment by clackner-gpa** [comment]
Sorry I misread this issue. this is not related to #13. Reopening

**Comment by clackner-gpa** [comment]
Fixed in `85208c6`
