### ISSUE TITLE
Version number overlaps with information in the sidebar

### ISSUE THREAD

**Issue by StephenCWills** [GridProtectionAlliance/SystemCenter#14]
You can see it in the bottom-left corner of the following image.

![image](https://user-images.githubusercontent.com/9203145/118851278-98ee5880-b89f-11eb-9c3c-66c160acebd4.png)

**Comment by clackner-gpa** [comment]
Technically the issue here is the Nav Bar needs to have a maximum height that adjusts based on the Browser window height. 

In addition we need to address the layout in Virtual Browsers (e.g. CITRIX) since some of the layouts use the outer window size instead of the virtual browser window size

**Comment by clackner-gpa** [comment]
Fixed in `607baa1`
