### ISSUE TITLE
Asset key update leads to invalid state (New Meter Wizard step 4)

### ISSUE THREAD

**Issue by StephenCWills** [GridProtectionAlliance/SystemCenter#9]
1. Navigate to step 4 of the New Meter wizard.
2. Add a new asset called "TEST" and associate all channels with this asset.
3. Use the pencil icon to update the new asset.
4. Change the Key of the asset to "TEST2" and select the `Add` button. Observe that the original asset doesn't change, and no new asset is added to the list.
5. Delete the "TEST" asset. Observe that all channels are still associated with something, but there is no longer any asset in the list  for them to be associated with.
6. Add a new asset called "TEST". Observe that no channels are available to be associated.
7. Proceed to the end of the wizard. You will receive the following error.

![image](https://user-images.githubusercontent.com/9203145/116930686-11151700-ac2e-11eb-8af3-2ca5957cd843.png)

---

The issues begin on step 4 of the instructions to reproduce. Either the user should be able to allowed to update the key of the edited asset or else the UI should disallow it. That should prevent this whole chain of events.

**Comment by clackner-gpa** [comment]
This issue has been resolved in `80d9d23`. The user can now edit the AssetKey and it will properly update.
